### ISSUE TITLE
微信IP

### ISSUE THREAD

**Issue by yanshihao3** [xujiaji/OneForAllApk#1]
微信支付，需要用 package 包名，如何动态改变

**Comment by xujiaji** [comment]
## 微信支付需要签名和包名
1. 包名动态配置如下：
![image](https://user-images.githubusercontent.com/16447251/48817579-180f7e00-ed82-11e8-804a-987bddafc67c.png)

2. 签名动态配置如下：
![image](https://user-images.githubusercontent.com/16447251/48817599-2e1d3e80-ed82-11e8-8a63-2bf30bf23806.png)

3. 需要注意：
![image](https://user-images.githubusercontent.com/16447251/48817626-50af5780-ed82-11e8-94b7-3ddf283eefef.png)

> 详细请参照：
https://blog.xujiaji.com/post/android-project-one-for-more

**Comment by yanshihao3** [comment]
微信支付需要 的是 配置文件AndroidManifest.xml中声明的package值 ，如何 更改这个和 applicationId 一致

**Comment by xujiaji** [comment]
不必要改，AndroidManifest.xml中的package只看做路径就可以了，包名就是applicationId。我用这种方式打包后的微信支付是没有问题的

**Comment by yanshihao3** [comment]
问题 是  我现在 支付不会回调 WXPayEntryActivity 这个 类

**Comment by yanshihao3** [comment]
https://www.jianshu.com/p/dca9c323c686 但是我不会写脚本

**Comment by xujiaji** [comment]
这是我的微信支付配置方式
![image](https://user-images.githubusercontent.com/16447251/48817894-80ab2a80-ed83-11e8-8e8f-1ee69c19a098.png)

**Comment by xujiaji** [comment]
原来还可以改路径666， 不过真没有必要。我打包的app微信支付都可以用的。你参照我上面的写法，设置别名的方式

**Comment by yanshihao3** [comment]
好的，我试试。谢谢

**Comment by yanshihao3** [comment]
成功了，非常感谢，谢谢

**Comment by xujiaji** [comment]
:clap:

**Comment by everyline** [comment]
图片看不到咋办

**Comment by xujiaji** [comment]
@everyline 哪里的图片看不到？

**Comment by everyline** [comment]
GitHub上传的图片




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xu Jiaji"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 下午2:54
收件人:&nbsp;"xujiaji/OneForAllApk"<OneForAllApk@noreply.github.com&gt;;
抄送:&nbsp;"746608431"<746608431@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xujiaji/OneForAllApk] 微信IP (#1)




@everyline 哪里的图片看不到？

**Comment by xujiaji** [comment]
@everyline 如果是Github上面的图片看不到的话，看看这篇文章的图片能看到不 https://blog.xujiaji.com/post/android-project-one-for-more

**Comment by everyline** [comment]
![图片](https://user-images.githubusercontent.com/8476579/72507178-5c12eb80-387e-11ea-9c79-2f53155ab270.png)
![图片](https://user-images.githubusercontent.com/8476579/72507207-69c87100-387e-11ea-83ae-aaffa91465b7.png)
![图片](https://user-images.githubusercontent.com/8476579/72507238-7cdb4100-387e-11ea-8dc9-4d7b2adcfd24.png)
这样写了之后 微信支付异常  哪里写的不对吗

**Comment by xujiaji** [comment]
微信能调用，只是微信支付异常？

**Comment by everyline** [comment]
是的 微信分享正常 qq 分享正常&nbsp; 只是支付宝和微信支付异常

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xu Jiaji"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 下午4:43
收件人:&nbsp;"xujiaji/OneForAllApk"<OneForAllApk@noreply.github.com&gt;;
抄送:&nbsp;"746608431"<746608431@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xujiaji/OneForAllApk] 微信IP (#1)




微信能调用，只是微信支付异常？

**Comment by xujiaji** [comment]
微信支付没有开通？

**Comment by xujiaji** [comment]
看看提示的什么错误

**Comment by everyline** [comment]
开了&nbsp; 以前都是正常的&nbsp; 只是现在只是多包名打包而已




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xu Jiaji"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 下午4:44
收件人:&nbsp;"xujiaji/OneForAllApk"<OneForAllApk@noreply.github.com&gt;;
抄送:&nbsp;"746608431"<746608431@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xujiaji/OneForAllApk] 微信IP (#1)




微信支付没有开通？

**Comment by xujiaji** [comment]
签名配置对应上吗？异常提示是什么

**Comment by everyline** [comment]
我看了下 有可能是微信支付改了配置&nbsp; 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xu Jiaji"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 下午4:51
收件人:&nbsp;"xujiaji/OneForAllApk"<OneForAllApk@noreply.github.com&gt;;
抄送:&nbsp;"746608431"<746608431@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xujiaji/OneForAllApk] 微信IP (#1)




签名配置对应上吗？

**Comment by everyline** [comment]
原来是微信支付&nbsp; body 限制 128个字符 导致支付异常




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xu Jiaji"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 下午4:51
收件人:&nbsp;"xujiaji/OneForAllApk"<OneForAllApk@noreply.github.com&gt;;
抄送:&nbsp;"746608431"<746608431@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xujiaji/OneForAllApk] 微信IP (#1)




签名配置对应上吗？
