### ISSUE TITLE
不生成R文件

### ISSUE THREAD

**Issue by yangfeng1994** [xujiaji/OneForAllApk#2]
您好，我下载了您的demo，发现没有生成R文件，但是还是可以运行的，不知道是什么原因造成的
![1543289154 1](https://user-images.githubusercontent.com/23312254/49056600-54862280-f237-11e8-8574-ca83da4bd21f.jpg)

**Comment by xujiaji** [comment]
改一下gradle版本试试

**Comment by yangfeng1994** [comment]
确实是因为gradle的原因。之前的项目也是复制包特别多，用的另一种方式，但导致项目特别大，刚好最近在Android developer上看到的，想研究一下，遇到了点小问题，恰好就看到您的了，中间的问题，完美解决。非常感谢。

**Comment by xujiaji** [comment]
:smile:
