### ISSUE TITLE
主项目依赖的子项目里面的资源不同怎么处理

### ISSUE THREAD

**Issue by tangchao0106** [xujiaji/OneForAllApk#3]
主项目依赖的子项目里面的资源不同怎么处理

**Comment by xujiaji** [comment]
和在主项目的`app/src`新建对应渠道的目录结构进行替换一个道理哦。只需要在`library/src`中同样操作就可以了

**Comment by tangchao0106** [comment]
主项目里面写的buildConfigField 子项目是不是引用不了？要怎么处理，大神demo可以完善下

**Comment by xujiaji** [comment]
确实引用不了，不是一般是主项目引用libray么。。。
你需要引用里面的什么主项目buildConfigField 的什么？

**Comment by tangchao0106** [comment]
子项目里面的 地址不同，不能直接使用buildConfigField 我都是间接处理的。在主项目里面往子项目常量赋值。子项目在判断

**Comment by tangchao0106** [comment]
还有个问题。打包生成apk的时候包名，怎么根据不同渠道，生成对应的渠道的中文名称。怎么写啊

**Comment by xujiaji** [comment]
哦，这样啊！可以这么操作：在library的gradle中配置对应渠道，添加library需要的buildConfigField 。主项目直接用library的BuildConfig就行了

**Comment by xujiaji** [comment]
我一会儿更新一下吧

**Comment by tangchao0106** [comment]
好的，打个中文名称的，不然每次打包好后还要手动改名称

**Comment by xujiaji** [comment]
已更新，请更新代码运行体验哈。[REAME](https://github.com/xujiaji/OneForAllApk/blob/master/README.md)最下面有简单进行介绍
