### ISSUE TITLE
ShareUserId能配置吗？

### ISSUE THREAD

**Issue by lfh1991** [xujiaji/OneForAllApk#4]
ShareUserId能配置吗？不同签名用不同的ShareUserId，或者有的签名需要ShareUserId，有的不要。可以配置吗？

**Comment by xujiaji** [comment]
这个我每没有试过，你可以试试将清单文件覆盖成你对应的配置，因该没有问题。或者你也可以等我晚些时间试试

**Comment by xujiaji** [comment]
经过测试有效可配置。
> ThreeApk和FourApk清单文件配置如下

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.xujiaji.oneforallapk"
    android:sharedUserId="com.xujiaji.shared">
</manifest>
```

测试文件[MainActivity](https://github.com/xujiaji/OneForAllApk/blob/master/app/src/main/java/com/xujiaji/oneforallapk/MainActivity.java)，测试了不同apk之间的资源访问。
- FourApk可访问ThreeApk资源
- OneApk和TwoApk不可访问ThreeApk资源

> 请运行四个渠道可观看，分别列出ThreeApk、TwoApk、FourApk截图（看橙色文字）
- ThreeApk 为被测试对象
- TwoApk 没有配置sharedUserId
- FourApk配置了和ThreeApk相同的sharedUserId

<div >
<img  src="https://user-images.githubusercontent.com/16447251/49517419-2065ce00-f8d7-11e8-902d-58ffc37b0b15.png" width="46%" height="auto">
<img  src="https://user-images.githubusercontent.com/16447251/49517442-2c519000-f8d7-11e8-99de-809264e32a55.png" width="46%" height="auto">
<img  src="https://user-images.githubusercontent.com/16447251/49517459-32477100-f8d7-11e8-8349-202ad2a1c616.png" width="46%" height="auto">
</div>
