### ISSUE TITLE
想知道您的这个目录是怎么创建的?

### ISSUE THREAD

**Issue by QiaoYang0923** [xujiaji/OneForAllApk#5]
想知道您的这个目录是怎么创建的,我是用的复制的方式,会在xml文件中报错URI is not registered (Settings | Languages & Frameworks | Schemas and DTDs)
![渠道](https://user-images.githubusercontent.com/23657667/65303154-cc02b500-dbaf-11e9-9fa7-dc32f8e26917.png)
![报错](https://user-images.githubusercontent.com/23657667/65303181-e2a90c00-dbaf-11e9-9a51-b8728508e330.png)

**Comment by xujiaji** [comment]
我是直接手动创建的目录，然后把需要替换的文件放到相对应的目录。
下面的这个报错，在当你选中了对应目录的渠道后因该就没有问题了
![](https://raw.githubusercontent.com/xujiaji/xujiaji.github.io/pictures/blog/one-for-more/20181113182242.png)

**Comment by QiaoYang0923** [comment]
感谢!




------------------ 原始邮件 ------------------
发件人: "Xu Jiaji"<notifications@github.com>;
发送时间: 2019年9月21日(星期六) 中午1:01
收件人: "xujiaji/OneForAllApk"<OneForAllApk@noreply.github.com>;
抄送: "乔阳"<962302437@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xujiaji/OneForAllApk] 想知道您的这个目录是怎么创建的? (#5)




我是直接手动创建的目录，然后把需要替换的文件放到相对应的目录。
 下面的这个报错，在当你选中了对应的渠道后因该就没有问题了
