### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by KotlinLan** [xujiaji/OneForAllApk#6]
根据你的配置方式，可以配置成功；但是现在遇到一个问题：
有些渠道的启动activity跟主项目的启动activity是不一样的，如果我新建一个跟主项目一样的，比如叫SplashActivity，这个时候IDE会提示类重复的错误，请问这种需求怎么解决？谢谢。

**Comment by xujiaji** [comment]
删掉主项目里的splashactivity，像这种项目就不要有主项目了，所有都看成渠道没有默认的

**Comment by xujiaji** [comment]
把主项目看成所有渠道的共有模块

**Comment by KotlinLan** [comment]
是不是说，把主项目的splashactivity这个类删除，然后在每一个渠道下面都创建一个splashactivity？

**Comment by xujiaji** [comment]
是的

**Comment by KotlinLan** [comment]
那在manifest清单文件中怎么注册呢？毕竟有些渠道连包名都不一样。

**Comment by xujiaji** [comment]
包名可以参考这个项目，在build.gradle中配置对应的applicationId就行了

**Comment by xujiaji** [comment]
你可以先运行一下这个案例项目先体验一下这个功能-编译多个不同签名、包名、资源等

**Comment by KotlinLan** [comment]
已经研究了很长一段时间，基本上都可以上线，现在需要加一个刚才说的需求，有些渠道splashactivity不一样，然后根据刚才的方法，在每个渠道下新建一个splashactivity，但是不知道怎么清单文件中注册？

**Comment by xujiaji** [comment]
不用改

**Comment by xujiaji** [comment]
你的aplashactivity只要和之前main目录结构相同的目录下面就行了

**Comment by KotlinLan** [comment]
好的，我试试。谢谢
